/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftprpc.h"

bool_t
xdr_sUser(xdrs, objp)
	register XDR *xdrs;
	sUser *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->login, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->passwd, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sNMod(xdrs, objp)
	register XDR *xdrs;
	sNMod *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->nombre, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->modo))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sFich(xdrs, objp)
	register XDR *xdrs;
	sFich *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->replica, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->descriptor))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sGet(xdrs, objp)
	register XDR *xdrs;
	sGet *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->replica, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->buffer, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->nbytes))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sPut(xdrs, objp)
	register XDR *xdrs;
	sPut *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_int(xdrs, &objp->descriptor))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->buffer, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->nbytes))
		return (FALSE);
	return (TRUE);
}
