/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ftprpc.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */


void
mi_ftp_rpc_1(host)
	char *host;
{
	CLIENT *clnt;
#ifndef	DEBUG
	clnt = clnt_create(host, MI_FTP_RPC, MI_FTP_RPC_VERS, "netpath");
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
#endif	/* DEBUG */

	Autenticacion (clnt);
	Interfaz(clnt);
#ifndef	DEBUG
	clnt_destroy(clnt);
#endif		/* DEBUG */
	exit(0);
}


main(argc, argv)
	int argc;
	char *argv[];
{
	char *host;

	if (argc < 2) {
		printf("usage:  %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	mi_ftp_rpc_1(host);
}
